language: rust

rust:
  - stable
  - beta
  - nightly
  - 1.28.0
  - 1.29.0
  - 1.30.0
  - 1.31.0
  - 1.32.0
  - 1.33.0

matrix:
  allow_failures:
    - rust: nightly
    - rust: 1.28.0
    - rust: 1.29.0
